version: '2'

services:
   ghost:
     depends_on:
       - db
     image: ghost:latest
     links:
       - db
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
   nginx:
     depends_on:
       - ghost
     image: nginx:latest
     links:
       - wordpress
     restart: always
     volumes:
       - "./.nginx:/etc/nginx"
     ports:
       - "8010:80"
       - "8443:443"

